# Generated by Django 3.2.6 on 2021-09-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_dataregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataregistro',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataregistro',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
